PATH_ROOT = "-root"
PATH_ARRAY = "-array"
PATH_OBJECT = "-obj"

SUB_OBJ = ":subObj"

RESPONSE_CODE_DIFF = "RESPONSE_CODE_DIFF"
KEY_SIZE_DIFF = "KEY_SIZE_DIFF"
KEY_NOT_MATCH = "KEY_NOT_MATCH"
ARRAY_SIZE_DIFF = "ARRAY_SIZE_DIFF"

VALUE_DIFF = "VALUE_DIFF"

DEBUG_LINE = "\n\t" + "=" * 20 + "\n"